apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataservice-etl
  name: dataservice-etl
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: dataservice-etl
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: dataservice-etl
    spec:
      containers:
      - env:
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: dataservice-etl
        resources:
          requests:
            memory: {{ required "Missing value FDK_DATASERVICE_ETL_MEMORY" .Values.FDK_DATASERVICE_ETL_MEMORY | quote }}
      restartPolicy: Always
status: {}
