name: Build and deploy to demo when merged to master

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy to demo environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup python environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

    - run: gcloud auth configure-docker

    - name: Build Docker image with GitHub commit sha tag and staging tag
      run: docker build . -t eu.gcr.io/digdir-fdk-infra/dataservice-etl:demo_latest

    - name: Publish docker image to Google Cloud
      run: docker -- push eu.gcr.io/digdir-fdk-infra/dataservice-etl

    - name: Apply Helm template
      uses: stefanprodan/kube-tools@v1
      with:
        helm: 2.14.3
        command: |
          helm init --client-only
          helm repo add dataservice-etl https://informasjonsforvaltning.github.io/dataservice-etl/
          helm fetch --untar --untardir ./helm dataservice-etl/dataservice-etl
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/dataservice-etl:$GITHUB_SHA" -f ./helm-sources/values/demo.yaml ./helm/dataservice-etl/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

    - name: Get kubeconfig file from GKE
      uses: machine-learning-apps/gke-kubeconfig@master
      with:
        application_credentials: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
        project_id: digdir-fdk-dev
        location_zone: europe-north1-a
        cluster_name: digdir-fdk-dev

    - name: Deploy to staging
      uses: docker://bitnami/kubectl:latest
      env:
        KUBECONFIG: '/github/workspace/.kube/config'
      with:
        args: "apply -f ./kubectlapply.yaml --force"
